name: al_quran_audio
description: "The Quran Audio Recitation App brings together a curated collection of 79 reciters, providing an immersive auditory experience of the Quran. With a focus on simplicity, accessibility, and quality, the app caters to users of all ages and preferences. Whether you are at home, commuting, or meditating, this app lets you carry the soul of the Quran wherever you go."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.0+7

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  icons_launcher: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^5.0.0-release-candidate-9.2.1
  url_launcher: ^6.3.1
  toastification: ^2.3.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  just_audio_background: ^0.0.1-beta.13
  fluentui_system_icons: ^1.1.270
  audio_video_progress_bar: ^2.0.3
  http: ^1.2.2
  persistent_bottom_nav_bar: ^6.2.1
  share_plus: ^10.1.3
  flutter_svg: ^2.0.16
  appwrite: ^13.1.1
  email_validator: ^3.0.0
  crypto: ^3.0.6
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/AlQuranAudio.jpg"
  platforms:
    android:
      enable: true
      image_path: "assets/AlQuranAudio.jpg"
      notification_image: "assets/AlQuranAudio.jpg"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/AlQuranAudio.jpg"
      adaptive_foreground_image: "assets/AlQuranAudio.jpg"
      adaptive_round_image: "assets/AlQuranAudio.jpg"
      adaptive_monochrome_image: "assets/AlQuranAudio.jpg"
    ios:
      enable: true
      image_path: "assets/AlQuranAudio.jpg"
      # For iOS 18+ (support dark and tinted)
      dark_path: "assets/AlQuranAudio.jpg"
      tinted_path: "assets/AlQuranAudio.jpg"
    web:
      enable: true
      image_path: "assets/AlQuranAudio.jpg"
      favicon_path: "assets/AlQuranAudio.jpg"
    macos:
      enable: false
      image_path: "assets/AlQuranAudio.jpg"
    windows:
      enable: false
      image_path: "assets/AlQuranAudio.jpg"
    linux:
      enable: false
      image_path: "assets/AlQuranAudio.jpg"
