List<Map<String, dynamic>> recitationsInfoList = [
  {"name": "Abdullah Awad al-Juhani", "id": "abdullaah_3awwaad_al-juhaynee"},
  {"name": "Abdullah Basfar", "id": "abdullaah_basfar"},
  {"name": "Abdur-Rahman as-Sudais", "id": "abdurrahmaan_as-sudays"},
  {"name": "Ali Abdur-Rahman al-Huthaify", "id": "huthayfi"},
  {"name": "AbdulMuhsin al-Qasim", "id": "abdul_muhsin_alqasim"},
  {"name": "AbdulBari ath-Thubaity", "id": "thubaity"},
  {"name": "Ahmed ibn Ali al-Ajmy", "id": "ahmed_ibn_3ali_al-3ajamy"},
  {"name": "AbdulAzeez al-Ahmad", "id": "abdulazeez_al-ahmad"},
  {"name": "AbdulBaset AbdulSamad [Murattal]", "id": "abdul_basit_murattal"},
  {"name": "AbdulWadud Haneef", "id": "abdulwadood_haneef"},
  {"name": "Aziz Alili", "id": "aziz_alili"},
  {
    "name": "AbdulBaset AbdulSamad [Mujawwad]",
    "id": "alhusaynee_al3azazee_with_children"
  },
  {
    "name": "Al-Hussayni Al-'Azazy (with Children)",
    "id": "alhusaynee_al3azazee_with_children"
  },
  {
    "name": "Abdur-Razaq bin Abtan al-Dulaimi [Mujawwad]",
    "id": "abdulrazaq_bin_abtan_al_dulaimi"
  },
  {"name": "Abdullah Khayat", "id": "khayat"},
  {"name": "Adel Kalbani", "id": "adel_kalbani"},
  {"name": "AbdulKareem Al Hazmi", "id": "abdulkareem_al_hazmi"},
  {"name": "Abdul-Mun'im Abdul-Mubdi'", "id": "abdulmun3im_abdulmubdi2"},
  {"name": "Abdur-Rashid Sufi", "id": "abdurrashid_sufi"},
  {"name": "Ahmad al-Huthaify", "id": "ahmad_alhuthayfi"},
  {
    "name": "Abu Bakr al-Shatri [Taraweeh]",
    "id": "abu_bakr_ash-shatri_tarawee7"
  },
  {"name": "Abdullah Matroud", "id": "abdullah_matroud"},
  {"name": "AbdulWadood Haneef", "id": "abdul_wadood_haneef_rare"},
  {"name": "Ahmad Nauina", "id": "ahmad_nauina"},
  {"name": "Akram Al-Alaqmi", "id": "akram_al_alaqmi"},
  {"name": "Ali Hajjaj Alsouasi", "id": "ali_hajjaj_alsouasi"},
  {"name": "Asim Abdul Aleem", "id": "asim_abdulaleem"},
  {"name": "Abdallah Abdal", "id": "abdallah_abdal"},
  {"name": "Abdullah Ali Jabir", "id": "ali_jaber"},
  {"name": "Bandar Baleela", "id": "bandar_baleela/complete"},
  {"name": "Dr. Shawqy Hamed [Murattal]", "id": "dr.shawqy_7amed/murattal"},
  {"name": "Fares Abbad", "id": "fares"},
  {"name": "Fatih Seferagic", "id": "fatih_seferagic"},
  {"name": "Hani ar-Rifai", "id": "rifai"},
  {"name": "Hamad Sinan", "id": "hamad_sinan"},
  {"name": "Hatem Farid", "id": "hatem_farid/collection"},
  {"name": "Ibrahim Al-Jibrin", "id": "jibreen"},
  {"name": "Imad Zuhair Hafez", "id": "imad_zuhair_hafez"},
  {"name": "Ibrahim Al Akhdar", "id": "ibrahim_al_akhdar"},
  {"name": "Idrees Abkar", "id": "idrees_akbar"},
  {"name": "Khalid al-Qahtani", "id": "khaalid_al-qahtaanee"},
  {"name": "Khalid Al Ghamdi", "id": "khalid_alghamdi/009.mp3"},
  {"name": "Khalifah Taniji", "id": "khalifah_taniji"},
  {"name": "Mishari Rashid al-`Afasy", "id": "mishaari_raashid_al_3afaasee"},
  {
    "name": "Muhammad Siddiq al-Minshawi",
    "id": "muhammad_siddeeq_al-minshaawee"
  },
  {"name": "Muhammad Jibreel", "id": "muhammad_jibreel/complete"},
  {"name": "Muhammad al-Mehysni", "id": "mehysni"},
  {"name": "Muhammad Siddiq al-Minshawi [Mujawwad]", "id": "minshawi_mujawwad"},
  {"name": "Muhammad al-Luhaidan", "id": "muhammad_alhaidan"},
  {"name": "Muhammad Abdul-Kareem", "id": "muhammad_abdulkareem"},
  {"name": "Mustafa al-`Azawi", "id": "mustafa_al3azzawi"},
  {"name": "Muhammad Hassan", "id": "mu7ammad_7assan"},
  {"name": "Mostafa Ismaeel", "id": "mostafa_ismaeel"},
  {"name": "Muhammad Sulaiman Patel", "id": "muhammad_patel"},
  {"name": "Mohammad Al-Tablawi", "id": "mohammad_ismaeel_almuqaddim"},
  {"name": "Mohammad Ismaeel Al-Muqaddim", "id": "mohammad_ismaeel_almuqaddim"},
  {"name": "Muhammad Ayyoob [Taraweeh]", "id": "muhammad_ayyoob_hq"},
  {"name": "Masjid Quba Taraweeh 1434", "id": "masjid_quba_1434"},
  {"name": "Muhammad Khaleel", "id": "muhammad_khaleel"},
  {
    "name": "Mahmoud Khaleel Al-Husary",
    "id": "mahmood_khaleel_al-husaree_iza3a"
  },
  {"name": "Mahmood Ali Al-Bana", "id": "mahmood_ali_albana"},
  {"name": "Maher al-Muaiqly", "id": "maher_almu3aiqly/year1440"},
  {"name": "Nabil ar-Rifai", "id": "nabil_rifa3i"},
  {"name": "Nasser Al Qatami", "id": "nasser_bin_ali_alqatami"},
  {"name": "Sa`ud ash-Shuraym", "id": "sa3ood_al-shuraym"},
  {"name": "Saad al-Ghamdi", "id": "sa3d_al-ghaamidi/complete"},
  {"name": "Sahl Yasin", "id": "sahl_yaaseen"},
  {"name": "Salah Bukhatir", "id": "salaah_bukhaatir"},
  {"name": "Sudais and Shuraym", "id": "sodais_and_shuraim"},
  {"name": "Saleh al Taleb", "id": "saleh_al_taleb"},
  {"name": "Salah al-Budair", "id": "salahbudair"},
  {"name": "Sadaqat `Ali", "id": "sadaqat_ali"},
  {"name": "Salah Al-Hashim", "id": "salah_alhashim"},
  {
    "name": "Tawfeeq ibn Sa`id as-Sawa'igh",
    "id": "tawfeeq_bin_saeed-as-sawaaigh"
  },
  {"name": "Wadee Hammadi Al Yamani", "id": "wadee_hammadi_al-yamani"},
  {"name": "Yasser ad-Dussary", "id": "yasser_ad-dussary"}
];
